### ISSUE TITLE
Ansible Service Broker can't work on origin 3.10 using latest image

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#102]
### Issue

Ansible Service Broker can't work on origin 3.10 using latest docker image - see this ticket for more [info](https://github.com/openshift/openshift-ansible/issues/9960)

### Solution
The workaround is to pass this parameter within the `cloud_inventory` file generated or when we execute the command from the terminal

```
ansible_service_broker_registry_tag=release-1.2
```

The workaround has been tested successfully on Centos7  + Origin 3.10

### Test result

ASB's log

```
Using config file mounted to /etc/ansible-service-broker/config.yaml
--
  | ============================================================
  | ==           Creating Ansible Service Broker...           ==
  | ============================================================
  | time="2018-09-11T05:04:09Z" level=info msg="Ansible Service Broker Version: 1.3.15"
  | time="2018-09-11T05:04:09Z" level=info msg="Initializing clients..."
  | time="2018-09-11T05:04:09Z" level=info msg="OpenShift version: v3.10.0+e3465d0-44"
  | time="2018-09-11T05:04:09Z" level=info msg="Kubernetes version: v1.10.0+b81c8f8"
  | time="2018-09-11T05:04:09Z" level=info msg="Empty AuthType. Assuming credentials are defined in the config... "
  | time="2018-09-11T05:04:09Z" level=info msg="== REGISTRY CX == "
  | time="2018-09-11T05:04:09Z" level=info msg="Name: dh"
  | time="2018-09-11T05:04:09Z" level=info msg="Type: dockerhub"
  | time="2018-09-11T05:04:09Z" level=info msg="Url: "
  | time="2018-09-11T05:04:09Z" level=info msg="Empty AuthType. Assuming credentials are defined in the config... "
  | time="2018-09-11T05:04:09Z" level=info msg="== REGISTRY CX == "
  | time="2018-09-11T05:04:09Z" level=info msg="Name: localregistry"
  | time="2018-09-11T05:04:09Z" level=info msg="Type: local_openshift"
  | time="2018-09-11T05:04:09Z" level=info msg="Url: "
  | ============================================================
  | ==           Starting Ansible Service Broker...           ==
  | ============================================================
  | time="2018-09-11T05:04:09Z" level=info msg="Initiating Recovery Process"
  | time="2018-09-11T05:04:09Z" level=info msg="Recovery complete"
  | time="2018-09-11T05:04:09Z" level=info msg="recover called"
  | time="2018-09-11T05:04:09Z" level=info msg="Broker configured to bootstrap on startup"
  | time="2018-09-11T05:04:09Z" level=info msg="Attempting bootstrap..."
  | time="2018-09-11T05:04:09Z" level=info msg="AnsibleBroker::Bootstrap"
  | time="2018-09-11T05:04:09Z" level=info msg="0 specs deleted"
  | time="2018-09-11T05:04:12Z" level=info msg="Bundles filtered by white/blacklist filter:\n\t-> ansibleplaybookbundle/kubevirt-ansible\n\t-> ansibleplaybookbundle/hello-world-apb\n\t-> ansibleplaybookbundle/rocketchat-apb\n\t-> ansibleplaybookbundle/rds-postgres-apb\n\t-> ansibleplaybookbundle/etherpad-apb\n\t-> ansibleplaybookbundle/wordpress-ha-apb\n\t-> ansibleplaybookbundle/hello-world-db-apb\n\t-> ansibleplaybookbundle/hastebin-apb\n\t-> ansibleplaybookbundle/pyzip-demo-apb\n\t-> ansibleplaybookbundle/jenkins-apb\n\t-> ansibleplaybookbundle/pyzip-demo-db-apb\n\t-> ansibleplaybookbundle/thelounge-apb\n\t-> ansibleplaybookbundle/manageiq-apb\n\t-> ansibleplaybookbundle/nginx-apb\n\t-> ansibleplaybookbundle/mediawiki-apb\n\t-> ansibleplaybookbundle/postgresql-apb\n\t-> ansibleplaybookbundle/mysql-apb\n\t-> ansibleplaybookbundle/mariadb-apb\n\t-> ansibleplaybookbundle/s2i-apb\n\t-> ansibleplaybookbundle/es-apb\n\t-> ansibleplaybookbundle/kibana-apb\n\t-> ansibleplaybookbundle/prometheus-apb\n\t-> ansibleplaybookbundle/awx-apb\n\t-> ansibleplaybookbundle/photo-album-demo-api-apb\n\t-> ansibleplaybookbundle/photo-album-demo-app-apb\n\t-> ansibleplaybookbundle/photo-album-demo-ext-api-apb\n\t-> ansibleplaybookbundle/iscsi-demo-target-apb\n\t-> ansibleplaybookbundle/mongodb-apb\n\t-> ansibleplaybookbundle/keycloak-apb\n\t-> ansibleplaybookbundle/virtualmachines-apb\n\t-> ansibleplaybookbundle/proxy-config-apb\n\t-> ansibleplaybookbundle/mssql-remote-apb\n\t-> ansibleplaybookbundle/dynamic-apb\n\t-> ansibleplaybookbundle/mssql-apb\n\t-> ansibleplaybookbundle/eclipse-che-apb\n\t-> ansibleplaybookbundle/manageiq-runner-apb\n\t-> ansibleplaybookbundle/import-vm-apb\n\t-> ansibleplaybookbundle/kubevirt-apb\n\t-> ansibleplaybookbundle/v2v-apb\n\t-> ansibleplaybookbundle/vnc-desktop-apb\n\t-> ansibleplaybookbundle/galera-apb\n\t-> ansibleplaybookbundle/openshift-logging-apb\n\t-> ansibleplaybookbundle/rhpam-apb\n\t-> ansibleplaybookbundle/tiller-apb\n\t-> ansibleplaybookbundle/standalone-cinder-apb\n\t-> ansibleplaybookbundl
  | e/gluster-s3object-apb\n\t-> ansibleplaybookbundle/origin-ansible-service-broker\n\t-> ansibleplaybookbundle/hello-world\n\t-> ansibleplaybookbundle/mediawiki123\n\t-> ansibleplaybookbundle/apb-base\n\t-> ansibleplaybookbundle/ansible-service-broker\n\t-> ansibleplaybookbundle/apb-tools\n\t-> ansibleplaybookbundle/manageiq-apb-runner\n\t-> ansibleplaybookbundle/py-zip-demo\n\t-> ansibleplaybookbundle/mediawiki\n\t-> ansibleplaybookbundle/asb-installer\n\t-> ansibleplaybookbundle/apb-assets-base\n\t-> ansibleplaybookbundle/photo-album-demo-app\n\t-> ansibleplaybookbundle/helm-bundle-base\n\t-> ansibleplaybookbundle/origin\n\t-> ansibleplaybookbundle/photo-album-demo-api\n\t-> ansibleplaybookbundle/deploy-broker\n\t-> ansibleplaybookbundle/vnc-client\n\t-> ansibleplaybookbundle/origin-service-catalog\n\t-> ansibleplaybookbundle/vnc-desktop\n\t-> ansibleplaybookbundle/origin-deployer\n\t-> ansibleplaybookbundle/origin-docker-registry\n\t-> ansibleplaybookbundle/origin-haproxy-router\n\t-> ansibleplaybookbundle/origin-pod\n\t-> ansibleplaybookbundle/origin-sti-builder\n\t-> ansibleplaybookbundle/origin-recycler\n"
  | time="2018-09-11T05:04:12Z" level=info msg="Validating specs..."
  | time="2018-09-11T05:04:12Z" level=info msg="All specs passed validation!"
  | time="2018-09-11T05:04:12Z" level=info msg="Bundles filtered by white/blacklist filter:\n\t-> openshift/dotnet\n\t-> openshift/dotnet-runtime\n\t-> openshift/httpd\n\t-> openshift/jenkins\n\t-> openshift/mariadb\n\t-> openshift/mongodb\n\t-> openshift/mysql\n\t-> openshift/nginx\n\t-> openshift/nodejs\n\t-> openshift/perl\n\t-> openshift/php\n\t-> openshift/postgresql\n\t-> openshift/python\n\t-> openshift/redis\n\t-> openshift/ruby\n\t-> openshift/wildfly\n"
  | time="2018-09-11T05:04:12Z" level=info msg="Validating specs..."
  | time="2018-09-11T05:04:12Z" level=info msg="All specs passed validation!"
  | time="2018-09-11T05:04:12Z" level=info msg="Broker successfully bootstrapped on startup"
  | time="2018-09-11T05:04:12Z" level=info msg="Listening on https://[::]:1338"
  | time="2018-09-11T05:04:12Z" level=info msg="Ansible Service Broker Starting"
```

ConfigMap's config

```
apiVersion: v1
data:
  broker-config: |
    registry:
      - type: dockerhub
        name: dh
        url:  
        org:  ansibleplaybookbundle
        tag:  release-1.2
        white_list: []

        auth_type: ""
        auth_name: ""
      - type: local_openshift
        name: localregistry
        namespaces: ['openshift']
        white_list: []

    dao:
      type: crd
    log:
      stdout: true
      level: info
      color: true
    openshift:
      host: ""
      ca_file: ""
      bearer_token_file: ""
      namespace: openshift-ansible-service-broker
      sandbox_role: edit
      image_pull_policy: Always
      keep_namespace: false
      keep_namespace_on_error: true
    broker:
      dev_broker: false
      bootstrap_on_startup: true
      refresh_interval: 600s
      launch_apb_on_bind: false
      output_request: false
      recovery: true
      ssl_cert_key: /etc/tls/private/tls.key
      ssl_cert: /etc/tls/private/tls.crt
      auto_escalate: False
      auth:
        - type: basic
          enabled: false
kind: ConfigMap
metadata:
  labels:
    app: openshift-ansible-service-broker
  name: broker-config
  namespace: openshift-ansible-service-broker
```

Catalog list

```
odo catalog list services
The following services can be deployed:
- dh-rhpam-apb
- dh-gluster-s3-apb
- dh-pyzip-demo-apb
- dh-openshift-logging-apb
- dh-nginx-apb
- dh-proxy-config-apb
- dh-eclipse-che-apb
- dh-galera-apb
- dh-vnc-desktop-apb
- dh-demo-api-apb
- dh-mssql-remote-apb
- dh-demo-ext-api-apb
- dh-v2v
- dh-standalone-cinder-apb
- mariadb-ephemeral
- mariadb-persistent
- mongodb-ephemeral
- mongodb-persistent
- mysql-ephemeral
- mysql-persistent
- postgresql-ephemeral
- postgresql-persistent
- redis-ephemeral
- redis-persistent
- dh-iscsi-demo-target-apb
- system
- 3scale-gateway
- cakephp-mysql-persistent
- cakephp-mysql-example
- dancer-mysql-persistent
- dancer-mysql-example
- django-psql-persistent
- django-psql-example
- dotnet-example
- dotnet-pgsql-persistent
- dotnet-runtime-example
- httpd-example
- jenkins-ephemeral
- jenkins-persistent
- nginx-example
- nodejs-mongo-persistent
- nodejs-mongodb-example
- amp-pvc
- rails-pgsql-persistent
- rails-postgresql-example
- amp-apicast-wildcard-router
- dh-kibana-apb
- dh-import-vm-apb
- dh-pyzip-demo-db-apb
- dh-manageiq-apb
- dh-awx-apb
- dh-blankvm-apb
- registry-console
- dh-hello-world-apb
- dh-wordpress-ha-apb
- dh-hastebin-apb
- dh-es-apb
- dh-hello-world-db-apb
- dh-keycloak-apb
- dh-rocketchat-apb
- dh-mssql-apb
- dh-rds-postgres-apb
- dh-etherpad-apb
- dh-demo-app-apb
- dh-dynamic-apb
- dh-mongodb-apb
- dh-thelounge-apb
- dh-jenkins-apb
- dh-prometheus-apb
- dh-tiller-apb
- dh-virtualization
```
