### ISSUE TITLE
Reuse RHTE ansible playbook to install halkyon

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/openshift-infra#130]
## Feature

Reuse or use RHTE ansible playbook to install halkyon as created here as it offers the possiblity to install kubedb, tekton, halkyon operator with only one task. See : 
https://github.com/redhat-cop/agnosticd/tree/development/ansible/roles/ocp-workload-dekorate-component-operator

@metacosm @geoand

**Comment by cmoulliard** [comment]
How can we modify the master config file within our halkyon role @geoand to execute the following steps ?
```
oc cluster down
vi /var/lib/origin/openshift.local.clusterup/kube-apiserver/master-config.yaml 
"WHY ==> to enable webhook admission and allow kubedb pod to start" 

Add

    ValidatingAdmissionWebhook:
     configuration:
      apiVersion: "apiserver.config.k8s.io/v1alpha1"
      kind: WebhookAdmission
      kubeConfigFile: "/dev/null"
    MutatingAdmissionWebhook:
     configuration:
      apiVersion: "apiserver.config.k8s.io/v1alpha1"
      kind: WebhookAdmission
      kubeConfigFile: "/dev/null"

after 

admissionConfig:
  pluginConfig:

and before

    openshift.io/ImagePolicy:
      configuration:
        apiVersion: v1
        executionRules:
        - matchImageAnnotations:
          - key: images.openshift.io/deny-execution
            value: "true"
          name: execution-denied
          onResources:
          - resource: pods
          - resource: builds
          reject: true
          skipOnResolutionFailure: true
        kind: ImagePolicyConfig
      location: ""

oc cluster up --public-hostname=116.203.87.224 --base-dir=/var/lib/origin/openshift.local.clusterup/
```
